### ISSUE TITLE
Training script/app

### ISSUE THREAD

**Issue by vvksh** [vvksh/lung-cancer-detection-pytorch#3]
reference implementation: https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p2ch11/training.py

**Comment by vvksh** [comment]
currently seeing this issue with commit: c81756a 

```
WARNING:util.utils:E0 Training ----/1497, starting
Traceback (most recent call last):
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/training.py", line 263, in <module>
    LunaTrainingApp().main()
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/training.py", line 257, in main
    trn_metrics_t = self.do_training(epoch_ndx=epoch_ndx, train_dl=train_dl)
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/training.py", line 104, in do_training
    for batch_ndx, batch_tup in batch_iter:
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/util/utils.py", line 97, in enumerate_with_estimate
    for (current_ndx, item) in enumerate(iter):
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/viveks/repos/deeplearningtuts/lung-cancer-detection-pytorch/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 54, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by vvksh** [comment]
had to set default num_workers to 4 to work on a mac
